version: '3'
services:
  marvel:
    build: .
    ports: 
      - "8080:8080"
    networks:
      - marvelNetwork
    depends_on:
      - db
    environment:
      DB_PASSWORD: /run/secrets/db_password
      DB_USERNAME: /run/secrets/db_user
      DB_NAME: /run/secrets/db_name
      DB_URL: jdbc:mariadb://db:3306/${DB_NAME}
    secrets:
      - db_user
      - db_password
      - db_name
  db:
    image: mariadb
    restart: always
    networks:
      - marvelNetwork
    secrets:
      - db_root_password
      - db_user
      - db_password
      - db_name
    environment:
      MYSQL_DATABASE: /run/secrets/db_name
      MYSQL_USER: /run/secrets/db_user
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_PASSWORD: /run/secrets/db_password
    volumes:
      - ./src/Marvel.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  marvelNetwork:
    driver: bridge

secrets:
  db_root_password:
    file: secrets/db_root_password.txt
  db_name: 
    file: secrets/db_name.txt
  db_user:  
    file: secrets/db_user.txt
  db_password:
    file: secrets/db_password.txt